BootStrap: docker
From: centos:centos7

%post
yum -y update && yum -y upgrade
yum -y install epel-release
yum -y install cmake3 make qt5-qtbase-devel gcc \
 avahi-compat-libdns_sd-devel gcc-c++ curl-devel \
 openssl-devel \
 libXtst-devel libXinerama-devel libICE-devel libXrandr-devel \
 wget rpm-build alien fakeroot

%runscript
# during the testing period using truatpasteurdotfr/barrier pre-released tarball
# final version should use the https://github.com/debauchee/barrier release versions

mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
wget https://github.com/debauchee/barrier/archive/v2.0.0.tar.gz -O ~/rpmbuild/SOURCES/barrier-2.0.0.tar.gz && \
wget https://raw.githubusercontent.com/truatpasteurdotfr/barrier/master/barrier.spec -O ~/rpmbuild/SPECS/barrier.spec  && \
rpmbuild -ba ~/rpmbuild/SPECS/barrier.spec 



